### ISSUE TITLE
Bug: Dual Sim Icons not working correctly

### ISSUE THREAD

**Issue by dryshirt** [franciscofranco/Demo-Mode-tile#7]
OnePlus 2
AOSP Extended v4.5-Official
Android 7.1.2

When activated, status bar icon of second sim is not filled. Not sure if you support people using custom ROMs, but it would be nice if you could fix it. Thank you for a simple, no-nonsense utility!

Permissions enabled:
![screenshot_20170925-173657](https://user-images.githubusercontent.com/24879294/30832211-481edaac-a218-11e7-8c2d-797177298a59.png)

Demo mode tile enabled:
![screenshot_20170925-173935](https://user-images.githubusercontent.com/24879294/30832290-8da93fae-a218-11e7-8e8d-10978abe6f98.png)

**Comment by noname2534** [comment]
+1

**Comment by binarynoise** [comment]
Hi, @dryshirt I read through the docs and probably found a fix. Do you still have the issue and want to try it out? Here is a test apk: 
[DemoModeTile-1.7-debug.apk.renamedTo.zip](https://github.com/franciscofranco/Demo-Mode-tile/files/6970486/DemoModeTile-1.7-r8debug.apk.renamedTo.zip)
You just need to rename the file back to .apk to try it out.
